name: test

on:
  pull_request:
    branches: 
    - development

jobs:
  dev_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         node-version: '12.x'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
